runtime: go
api_version: go1

application: uber-challenge-148819
version: alpha-002

handlers:
- url: /favicon\.ico
  static_files: static/favicon.ico
  upload: static/favicon\.ico
- url: /.*
  script: _go_app

skip_files:
- ^\..*
- ^.*\.iml$
- ^.*\.md$
- ^data-source-name$
