runtime: go
api_version: go1

application: uber-challenge-148819
version: 001

handlers:
- url: /favicon\.ico
  static_files: static/favicon.ico
  upload: static/favicon\.ico
- url: /(.*\.js)
  mime_type: text/javascript
  static_files: static/\1
  upload: static/.*
- url: /.*
  script: _go_app

skip_files:
- ^\..*
- ^.*\.iml$
- ^.*\.md$
- ^data-source-name$
